name: Documentation

on:
  push:
    branches:
      -  main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate doc
    steps:
      - name: git-checkout
        uses: actions/checkout@v2
      
      - name: dart
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.1'
          channel: 'stable'

      - name: Install deps
        run: flutter pub get
        working-directory: ./trelltech

      - name: Generate doc
        run: dart doc .
        working-directory: ./trelltech

      - name: Push
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: documentation # The branch name where you want to push the assets
          FOLDER: trelltech/doc # The directory where your assets are generated
          MESSAGE: "Build: ({sha}) {msg}" # The commit message